builds:
  - binary: mackerel-plugin-pinglatency
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: kmuto
    name: mackerel-plugin-pinglatency
