version: 2
builds:
  - env:
    - CGO_ENABLED=0
    - PACKAGE_PATH=github.com/kmuto/mackerel-plugin-pinglatency/lib
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X {{ .Env.PACKAGE_PATH }}.version={{ .Version }}
      - -X {{ .Env.PACKAGE_PATH }}.revision={{ .ShortCommit }}
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
